// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIdP1MixBAkMjSdWq30GX2IMfOmNl_LZU',
    appId: '1:324897105944:web:4e7f8c07d0763ec755fb6d',
    messagingSenderId: '324897105944',
    projectId: 'favoriteplaces-a3f97',
    authDomain: 'favoriteplaces-a3f97.firebaseapp.com',
    storageBucket: 'favoriteplaces-a3f97.firebasestorage.app',
    measurementId: 'G-37918W5V51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7c1Won8LKjG2z5pV1px-8uOf9SkdeP_E',
    appId: '1:324897105944:android:82f6466d921c3f9d55fb6d',
    messagingSenderId: '324897105944',
    projectId: 'favoriteplaces-a3f97',
    storageBucket: 'favoriteplaces-a3f97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocc5a3NEHFP2Vy6JweVX8GxdTzy7ODPw',
    appId: '1:324897105944:ios:47389d1be353e14f55fb6d',
    messagingSenderId: '324897105944',
    projectId: 'favoriteplaces-a3f97',
    storageBucket: 'favoriteplaces-a3f97.firebasestorage.app',
    iosBundleId: 'com.example.smartPlaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCocc5a3NEHFP2Vy6JweVX8GxdTzy7ODPw',
    appId: '1:324897105944:ios:47389d1be353e14f55fb6d',
    messagingSenderId: '324897105944',
    projectId: 'favoriteplaces-a3f97',
    storageBucket: 'favoriteplaces-a3f97.firebasestorage.app',
    iosBundleId: 'com.example.smartPlaces',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIdP1MixBAkMjSdWq30GX2IMfOmNl_LZU',
    appId: '1:324897105944:web:d21d92984fe2ddd055fb6d',
    messagingSenderId: '324897105944',
    projectId: 'favoriteplaces-a3f97',
    authDomain: 'favoriteplaces-a3f97.firebaseapp.com',
    storageBucket: 'favoriteplaces-a3f97.firebasestorage.app',
    measurementId: 'G-2SC87RDXVV',
  );
}
